[server]
port = 8080

[adapter.redis]
host = "127.0.0.1"
port = 6379
password = ""

[file_storage]
storage_kind = "filesystem"

[cache_storage]
storage_kind = "filesystem"

[file_storage.filesystem]
mount_dir = "./mnt"

[cache_storage.filesystem]
mount_dir = "./mnt"

[apikey]
storage_kind = "redis"

[named_transformation]
storage_kind = "redis"

[metadata]
storage_kind = "redis"
